package painel_saude.application.port.output {

    interface "UserRepository" as port_user_repository {
        +find_by_id(id: int) : User
        +find_by_email(email: string) : User
        +save(user: User) : void
    }

}
