package painel_saude.application.usecase {

    class "AuthenticateUserByTokenService" as usecase_authenticate_user_by_token_service {
        +authenticate(request: AuthenticateUserByTokenRequest) : AuthenticateUserByTokenResponse
    }

}
